#!/usr/bin/env python3
"""Wrap metrics_summary.json as a JS assignment so the viewer works over file://.

Browsers block fetch() from file:// URLs, so a page opened by double-clicking cannot
read a sibling JSON file. A <script> tag can. This writes the same bytes into
docs/metrics_data.js as `window.AFC_METRICS = {...}` -- no transformation, no
computation, just a different transport. The viewer still prefers fetch() when it is
actually served, and falls back to a file picker if neither works.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "metrics_summary.json"
DST = ROOT / "docs" / "metrics_data.js"


def main() -> int:
    if not SRC.exists():
        print(f"make_viewer_data: {SRC.name} not found -- run `make metrics` first",
              file=sys.stderr)
        return 1
    payload = json.loads(SRC.read_text())
    DST.parent.mkdir(exist_ok=True)
    DST.write_text(
        "// Generated by tools/make_viewer_data.py -- do not edit.\n"
        "// Verbatim copy of metrics_summary.json, wrapped so the viewer can be\n"
        "// opened directly from disk (browsers block fetch() over file://).\n"
        "window.AFC_METRICS = " + json.dumps(payload, indent=2) + ";\n"
    )
    print(f"make_viewer_data: wrote {DST.relative_to(ROOT)} "
          f"({DST.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
